INSERT INTO devices_dictionary VALUES ("A1-810","Acer","Iconia A1-810","Android",""),
("ALCATEL_ONE_TOUCH_Fierce","Alcatel","One Touch Fierce","Android",""),
("ALCATEL_ONE_TOUCH_7041X","Alcatel","One Touch Pop C7","Android",""),
("ALCATEL_ONE_TOUCH_5035X","Alcatel","One Touch X Pop","Android",""),
("google_sdk","Android","Emulator","Android",""),
("iPad1,1","Apple","iPad","iOS","Original/1st Gen"),
("iPad2,1","Apple","iPad 2","iOS","Wi-Fi Only"),
("iPad2,4","Apple","iPad 2","iOS","Wi-Fi Only, 32nm CPU"),
("iPad2,3","Apple","iPad 2","iOS","Wi-Fi/CDMA/GPS"),
("iPad2,2","Apple","iPad 2","iOS","Wi-Fi/GSM/GPS"),
("iPad3,1","Apple","iPad 3rd Gen","iOS","Wi-Fi Only"),
("iPad3,3","Apple","iPad 3rd Gen","iOS","Wi-Fi/Cellular AT&T/GPS"),
("iPad3,2","Apple","iPad 3rd Gen","iOS","Wi-Fi/Cellular Verizon/GPS"),
("iPad3,4","Apple","iPad 4th Gen","iOS","Wi-Fi Only"),
("iPad3,5","Apple","iPad 4th Gen","iOS","Wi-Fi/AT&T/GPS"),
("iPad3,6","Apple","iPad 4th Gen","iOS","Wi-Fi/Verizon & Sprint/GPS"),
("iPad4,1","Apple","iPad Air","iOS","Wi-Fi Only"),
("iPad4,2","Apple","iPad Air","iOS","Wi-Fi/Cellular"),
("iPad4,3","Apple","iPad Air","iOS","Wi-Fi/TD-LTE - China"),
("iPad5,3","Apple","iPad Air 2","iOS","Wi-Fi Only"),
("iPad5,4","Apple","iPad Air 2","iOS","Wi-Fi/Cellular"),
("iPad2,5","Apple","iPad mini","iOS","Wi-Fi Only/1st Gen"),
("iPad2,6","Apple","iPad mini","iOS","Wi-Fi/AT&T/GPS - 1st Gen"),
("iPad2,7","Apple","iPad mini","iOS","Wi-Fi/VZ & Sprint/GPS - 1st Gen"),
("iPad4,6","Apple","iPad mini 2","iOS","Retina/2nd Gen, China"),
("iPad4,4","Apple","iPad mini 2","iOS","Retina/2nd Gen, Wi-Fi Only"),
("iPad4,5","Apple","iPad mini 2","iOS","Retina/2nd Gen, Wi-Fi/Cellular"),
("iPad4,7","Apple","iPad mini 3","iOS","Wi-Fi Only"),
("iPad4,8","Apple","iPad mini 3","iOS","Wi-Fi/Cellular"),
("iPhone1,1","Apple","iPhone","iOS","Original/1st Gen/EDGE"),
("iPhone1,2","Apple","iPhone 3G","iOS",""),
("iPhone2,1","Apple","iPhone 3GS","iOS",""),
("iPhone3,3","Apple","iPhone 4","iOS","CDMA/Verizon/Sprint"),
("iPhone3,1","Apple","iPhone 4","iOS","GSM"),
("iPhone4,1","Apple","iPhone 4S","iOS",""),
("iPhone5,2","Apple","iPhone 5","iOS","CDMA/LTE"),
("iPhone5,1","Apple","iPhone 5","iOS","GSM/LTE"),
("iPhone5,4","Apple","iPhone 5c","iOS","Global"),
("iPhone5,3","Apple","iPhone 5c","iOS","GSM"),
("iPhone6,2","Apple","iPhone 5s","iOS","Global"),
("iPhone6,1","Apple","iPhone 5s","iOS","GSM"),
("iPhone7,2","Apple","iPhone 6","iOS",""),
("iPhone7,1","Apple","iPhone 6 Plus","iOS",""),
("iPod1,1","Apple","iPod touch","iOS","Original/1st Gen"),
("iPod2,1","Apple","iPod touch 2nd Gen","iOS",""),
("iPod3,1","Apple","iPod touch 3rd Gen","iOS",""),
("iPod4,1","Apple","iPod touch 4th Gen","iOS",""),
("iPod5,1","Apple","iPod touch 5th Gen","iOS",""),
("Transformer_TF101","ASUS","Eee Pad Transformer","Android",""),
("Transformer_Prime_TF201","ASUS","Eee Pad Transformer Prime","Android",""),
("ME173X","ASUS","MeMO Pad HD 7","Android",""),
("Nexus_7","ASUS","Nexus 7","Android",""),
("ASUS_Transformer_Pad_TF300T","ASUS","Transformer Pad","Android",""),
("ASUS_Transformer_Pad_TF700T","ASUS","Transformer Pad Infinity","Android",""),
("bq_Aquaris_5","bq","Aquaris 5","Android",""),
("bq_Aquaris_5_HD","bq","Aquaris 5 HD","Android",""),
("Aquaris_E4.5","bq","Aquaris E4.5","Android",""),
("5860E","Coolpad","Quattro 4G","Android",""),
("CUBOT_ONE","Cubot","One","Android",""),
("Nexus_10","Google","Nexus 10","Android",""),
("Nexus_4","Google","Nexus 4","Android",""),
("HTC_Amaze_4G","HTC","Amaze 4G","Android",""),
("HTC_Desire","HTC","Desire","Android",""),
("HTC_Desire_500","HTC","Desire 500","Android",""),
("HTC_Desire_C","HTC","Desire C","Android",""),
("Desire_HD","HTC","Desire HD","Android",""),
("HTC_Desire_HD_A9191","HTC","Desire HD","Android",""),
("HTC_Desire_S","HTC","Desire S","Android",""),
("HTC6435LVW","HTC","Droid DNA","Android",""),
("ADR6300","HTC","Droid Incredible","Android",""),
("ADR6350","HTC","Droid Incredible 2","Android",""),
("ADR6410LVW","HTC","Droid Incredible 4G","Android",""),
("EVO","HTC","Evo","Android",""),
("PG86100","HTC","Evo 3D","Android",""),
("PC36100","HTC","Evo 4G","Android",""),
("HTCEVODesign4G","HTC","Evo Design 4G","Android",""),
("PH44100","HTC","Evo Design 4G","Android",""),
("PG06100","HTC","EVO Shift 4G","Android",""),
("HTCEVOV4G","HTC","Evo V 4G","Android",""),
("HTC_Glacier","HTC","Glacier","Android",""),
("HTC_Incredible_S","HTC","Incredible S","Android",""),
("myTouch_4G_Slide","HTC","myTouch 4G Slide","Android",""),
("HTC6500LVW","HTC","One","Android",""),
("HTC_One","HTC","One","Android",""),
("HTCONE","HTC","One","Android",""),
("HTC_PN071","HTC","One","Android",""),
("831C","HTC","One M8","Android",""),
("HTC6525LVW","HTC","One M8","Android",""),
("HTC_One_M8","HTC","One M8","Android",""),
("HTC_One_mini","HTC","One mini","Android",""),
("HTC_One_S","HTC","One S","Android",""),
("HTC_VLE_U","HTC","One S","Android",""),
("HTC_One_V","HTC","One V","Android",""),
("HTC_One_X","HTC","One X","Android",""),
("HTC_One_X+","HTC","One X+","Android",""),
("ADR6425LVW","HTC","Rezound 4G","Android",""),
("ADR6330VW","HTC","Rhyme","Android",""),
("HTC_Sensation_Z710e","HTC","Sensation","Android",""),
("HTC_Sensation_4G","HTC","Sensation 4G","Android",""),
("ADR6400L","HTC","Thunderbolt","Android",""),
("HTC_PH39100","HTC","Vivid 4G","Android",""),
("HUAWEI_G510-0251","Huawei","Ascend G510","Android",""),
("Orange_Daytona","Huawei","Ascend G510","Android",""),
("HUAWEI_P6-U06","Huawei","Ascend P6","Android",""),
("HUAWEI_Y300-0100","Huawei","Ascend Y300","Android",""),
("CM990","Huawei","Evolution III","Android",""),
("KFOT","Kindle","Fire","Android",""),
("Kindle_Fire","Kindle","Fire","Android",""),
("KFTT","Kindle","Fire HD 7","Android",""),
("KFJWA","Kindle","Fire HD 8.9","Android",""),
("KFJWI","Kindle","Fire HD 8.9","Android",""),
("C5170","Kyocera","Hydro","Android",""),
("C5155","Kyocera","Rise","Android",""),
("LG-MS910","LG","Esteem","Android",""),
("LG-D686","LG","G Pro Lite Dual","Android",""),
("LG-D800","LG","G2","Android",""),
("LG-D801","LG","G2","Android",""),
("LG-D802","LG","G2","Android",""),
("LG-LS980","LG","G2","Android",""),
("VS980_4G","LG","G2","Android",""),
("LG-D620","LG","G2 Mini","Android",""),
("LG-P999","LG","G2X P999","Android",""),
("LG-D850","LG","G3","Android",""),
("LG-D851","LG","G3","Android",""),
("LG-D855","LG","G3","Android",""),
("VS985_4G","LG","G3 4G","Android",""),
("VS840_4G","LG","Lucid 4G","Android",""),
("LG-MS770","LG","Motion 4G","Android",""),
("LG-E739","LG","MyTouch e739","Android",""),
("LG-C800","LG","myTouch Q","Android",""),
("LG-VM696","LG","Optimus Elite","Android",""),
("LG-LS720","LG","Optimus F3","Android",""),
("LGMS500","LG","Optimus F6","Android",""),
("LG-E970","LG","Optimus G","Android",""),
("LG-LS970","LG","Optimus G","Android",""),
("LG-E980","LG","Optimus G Pro","Android",""),
("LG-E411g","LG","Optimus L1 II","Android",""),
("LG-E425g","LG","Optimus L3 II","Android",""),
("LG-E440g","LG","Optimus L4 II","Android",""),
("LG-E610","LG","Optimus L5","Android",""),
("LG-E612g","LG","Optimus L5 Dual","Android",""),
("LG-E460","LG","Optimus L5 II","Android",""),
("LGMS323","LG","Optimus L70","Android",""),
("LGMS769","LG","Optimus L9","Android",""),
("LG-P760","LG","Optimus L9","Android",""),
("LG-P768","LG","Optimus L9","Android",""),
("LG-P769","LG","Optimus L9","Android",""),
("LG-D415","LG","Optimus L90","Android",""),
("LGL55C","LG","Optimus Q","Android",""),
("LS670","LG","Optimus S","Android",""),
("LG-P509","LG","Optimus T","Android",""),
("VM670","LG","Optimus V","Android",""),
("VS910_4G","LG","Revolution 4G","Android",""),
("VS930_4G","LG","Spectrum 2","Android",""),
("VS920_4G","LG","Spectrum 4G","Android",""),
("LG-LG730","LG","Venice","Android",""),
("LG-LS840","LG","Viper","Android",""),
("LGLS740","LG","Volt","Android",""),
("MB865","Motorola","Atrix 2","Android",""),
("MB860","Motorola","Atrix 4G","Android",""),
("MB886","Motorola","Atrix HD","Android",""),
("Droid","Motorola","Droid","Android",""),
("DROID2","Motorola","Droid 2","Android",""),
("DROID2_GLOBAL","Motorola","Droid 2 Global","Android",""),
("DROID3","Motorola","Droid 3","Android",""),
("DROID4","Motorola","Droid 4","Android",""),
("DROID_BIONIC","Motorola","Droid Bionic","Android",""),
("XT1030","Motorola","Droid Mini","Android",""),
("DROID_Pro","Motorola","Droid Pro","Android",""),
("DROID_RAZR","Motorola","Droid Razr","Android",""),
("DROID_RAZR_HD","Motorola","Droid Razr HD","Android",""),
("XT907","Motorola","Droid Razr M","Android",""),
("XT1080","Motorola","Droid Ultra","Android",""),
("DROIDX","Motorola","Droid X","Android",""),
("DROID_X2","Motorola","Droid X2","Android",""),
("Motorola_Electrify","Motorola","Electrify","Android",""),
("XT1028","Motorola","Moto G","Android",""),
("XT1031","Motorola","Moto G","Android",""),
("XT1032","Motorola","Moto G","Android",""),
("XT1033","Motorola","Moto G","Android",""),
("XT1049","Motorola","Moto X","Android",""),
("XT1053","Motorola","Moto X","Android",""),
("XT1056","Motorola","Moto X","Android",""),
("XT1058","Motorola","Moto X","Android",""),
("XT1060","Motorola","Moto X","Android",""),
("XT897","Motorola","Photo Q","Android",""),
("MB855","Motorola","Photon 4G","Android",""),
("MOTWX435KT","Motorola","Triumph","Android",""),
("Xoom","Motorola","Xoom","Android",""),
("Nexus_5","Nexus","5","Android",""),
("A0001","OnePlus","One","Android",""),
("PantechP9070","Pantech","Burst","Android",""),
("SCH-R720","Samsung","Admire","Android",""),
("SAMSUNG-SGH-I897","Samsung","Captivate","Android",""),
("SAMSUNG-SGH-I927","Samsung","Captivate Glide","Android",""),
("SPH-D600","Samsung","Conquer 4G","Android",""),
("SCH-I510","Samsung","Droid Charge","Android",""),
("SPH-D710","Samsung","Epic","Android",""),
("SPH-D700","Samsung","Epic 4G","Android",""),
("SGH-T679","Samsung","Exhibit II","Android",""),
("SCH-I500","Samsung","Fascinate","Android",""),
("GT-S5830i","Samsung","Galaxy Ace","Android",""),
("GT-S5830","Samsung","Galaxy Ace","Android",""),
("GT-I8160","Samsung","Galaxy Ace 2","Android",""),
("GT-S7560M","Samsung","Galaxy Ace II X","Android",""),
("SCH-S738C","Samsung","Galaxy Centura","Android",""),
("GT-I8260","Samsung","Galaxy Core","Android",""),
("SGH-T599N","Samsung","Galaxy Exhibit","Android",""),
("SM-G3815","Samsung","Galaxy Express II","Android",""),
("GT-S6810P","Samsung","Galaxy Fame","Android",""),
("GT-I9082","Samsung","Galaxy Grand","Android",""),
("SM-G7102","Samsung","Galaxy Grand II","Android",""),
("GT-I9060","Samsung","Galaxy Grand Neo","Android",""),
("GT-I9063T","Samsung","Galaxy Grand Neo Duos","Android",""),
("SGH-T399","Samsung","Galaxy Light","Android",""),
("SAMSUNG-SGH-I527","Samsung","Galaxy Mega","Android",""),
("GT-S5570","Samsung","Galaxy Mini","Android",""),
("Galaxy_Nexus","Samsung","Galaxy Nexus","Android",""),
("GT-N7000","Samsung","Galaxy Note","Android",""),
("SAMSUNG-SGH-I717","Samsung","Galaxy Note","Android",""),
("GT-N8010","Samsung","Galaxy Note 10.1","Android",""),
("GT-N8013","Samsung","Galaxy Note 10.1","Android",""),
("SM-P600","Samsung","Galaxy Note 10.1","Android",""),
("SAMSUNG-SM-N900A","Samsung","Galaxy Note 3","Android",""),
("SM-N9005","Samsung","Galaxy Note 3","Android",""),
("SM-N9006","Samsung","Galaxy Note 3","Android",""),
("SM-N900P","Samsung","Galaxy Note 3","Android",""),
("SM-N900","Samsung","Galaxy Note 3","Android",""),
("SM-N900T","Samsung","Galaxy Note 3","Android",""),
("SM-N900V","Samsung","Galaxy Note 3","Android",""),
("SM-N900W8","Samsung","Galaxy Note 3","Android",""),
("SM-N7505","Samsung","Galaxy Note 3 Neo","Android",""),
("SAMSUNG-SM-N910A","Samsung","Galaxy Note 4","Android",""),
("SM-N910T","Samsung","Galaxy Note 4","Android",""),
("SM-N910V","Samsung","Galaxy Note 4","Android",""),
("GT-N5110","Samsung","Galaxy Note 8.0","Android",""),
("GT-N7100","Samsung","Galaxy Note II","Android",""),
("GT-N7105","Samsung","Galaxy Note II","Android",""),
("GT-N7105T","Samsung","Galaxy Note II","Android",""),
("SAMSUNG-SGH-I317","Samsung","Galaxy Note II","Android",""),
("SCH-I605","Samsung","Galaxy Note II","Android",""),
("SGH-I317M","Samsung","Galaxy Note II","Android",""),
("SGH-T889","Samsung","Galaxy Note II","Android",""),
("SHV-E250S","Samsung","Galaxy Note II","Android",""),
("SPH-L900","Samsung","Galaxy Note II","Android",""),
("GT-S5301L","Samsung","Galaxy Pocket Plus","Android",""),
("SPH-M820-BST","Samsung","Galaxy Prevail","Android",""),
("SPH-M840","Samsung","Galaxy Prevail 2","Android",""),
("SPH-M830","Samsung","Galaxy Rush","Android",""),
("GT-I9000","Samsung","Galaxy S","Android",""),
("SGH-T959V","Samsung","Galaxy S 4G","Android",""),
("GT-I9070","Samsung","Galaxy S Advance","Android",""),
("SGH-T769","Samsung","Galaxy S Blaze","Android",""),
("GT-S7562","Samsung","Galaxy S Duos","Android",""),
("GT-I9100M","Samsung","Galaxy S II","Android",""),
("GT-I9100P","Samsung","Galaxy S II","Android",""),
("GT-I9100","Samsung","Galaxy S II","Android",""),
("GT-I9100T","Samsung","Galaxy S II","Android",""),
("SAMSUNG-SGH-I777","Samsung","Galaxy S II","Android",""),
("SGH-I727R","Samsung","Galaxy S II","Android",""),
("SGH-T989D","Samsung","Galaxy S II","Android",""),
("SGH-T989","Samsung","Galaxy S II","Android",""),
("SPH-D710BST","Samsung","Galaxy S II","Android",""),
("SPH-D710VMUB","Samsung","Galaxy S II","Android",""),
("GT-I9300","Samsung","Galaxy S III","Android",""),
("GT-I9300T","Samsung","Galaxy S III","Android",""),
("GT-I9305","Samsung","Galaxy S III","Android",""),
("GT-I9305T","Samsung","Galaxy S III","Android",""),
("SAMSUNG-SGH-I747","Samsung","Galaxy S III","Android",""),
("SCH-I535","Samsung","Galaxy S III","Android",""),
("SCH-R530M","Samsung","Galaxy S III","Android",""),
("SCH-R530U","Samsung","Galaxy S III","Android",""),
("SGH-I747M","Samsung","Galaxy S III","Android",""),
("SGH-T999L","Samsung","Galaxy S III","Android",""),
("SGH-T999","Samsung","Galaxy S III","Android",""),
("SGH-T999V","Samsung","Galaxy S III","Android",""),
("SHV-E210S","Samsung","Galaxy S III","Android",""),
("SPH-L710","Samsung","Galaxy S III","Android",""),
("GT-I8190N","Samsung","Galaxy S III Mini","Android",""),
("GT-I8190","Samsung","Galaxy S III Mini","Android",""),
("GT-I9001","Samsung","Galaxy S Plus","Android",""),
("SGH-T959","Samsung","Galaxy S Vibrant","Android",""),
("GT-I9105P","Samsung","Galaxy S2 Plus","Android",""),
("SCH-R530C","Samsung","Galaxy S3","Android",""),
("SHV-E210K","Samsung","Galaxy S3","Android",""),
("GT-I8190L","Samsung","Galaxy S3 Mini","Android",""),
("SAMSUNG-SM-G730A","Samsung","Galaxy S3 Mini","Android",""),
("GT-I9500","Samsung","Galaxy S4","Android",""),
("GT-I9505","Samsung","Galaxy S4","Android",""),
("GT-I9506","Samsung","Galaxy S4","Android",""),
("SAMSUNG-SGH-I337","Samsung","Galaxy S4","Android",""),
("SCH-I545","Samsung","Galaxy S4","Android",""),
("SCH-R970","Samsung","Galaxy S4","Android",""),
("SGH-I337M","Samsung","Galaxy S4","Android",""),
("SGH-M919","Samsung","Galaxy S4","Android",""),
("SPH-L720","Samsung","Galaxy S4","Android",""),
("SPH-L720T","Samsung","Galaxy S4","Android",""),
("SAMSUNG-SGH-I537","Samsung","Galaxy S4 Active","Android",""),
("GT-I9195","Samsung","Galaxy S4 Mini","Android",""),
("SCH-I435","Samsung","Galaxy S4 Mini","Android",""),
("GT-I9192","Samsung","Galaxy S4 Mini Duos","Android",""),
("SAMSUNG-SM-G900A","Samsung","Galaxy S5","Android",""),
("SM-G900F","Samsung","Galaxy S5","Android",""),
("SM-G900I","Samsung","Galaxy S5","Android",""),
("SM-G900P","Samsung","Galaxy S5","Android",""),
("SM-G900T","Samsung","Galaxy S5","Android",""),
("SM-G900V","Samsung","Galaxy S5","Android",""),
("SM-G900W8","Samsung","Galaxy S5","Android",""),
("SAMSUNG-SM-G870A","Samsung","Galaxy S5 Active","Android",""),
("SCH-I200","Samsung","Galaxy Stellar","Android",""),
("SCH-I415","Samsung","Galaxy Stratosphere II","Android",""),
("GT-P7510","Samsung","Galaxy Tab 10.1","Android",""),
("GT-P3100","Samsung","Galaxy Tab 2","Android",""),
("GT-P3110","Samsung","Galaxy Tab 2","Android",""),
("GT-P5110","Samsung","Galaxy Tab 2","Android",""),
("GT-P5113","Samsung","Galaxy Tab 2 10.1","Android",""),
("GT-P3113","Samsung","Galaxy Tab 2 7.0","Android",""),
("GT-P5210","Samsung","Galaxy Tab 3 10.1","Android",""),
("SM-T210R","Samsung","Galaxy Tab 3 7.0","Android",""),
("SM-T217S","Samsung","Galaxy Tab 3 7.0","Android",""),
("SM-T310","Samsung","Galaxy Tab 3 8.0","Android",""),
("SCH-I800","Samsung","Galaxy Tab 7.0","Android",""),
("GT-S7580","Samsung","Galaxy Trend Plus","Android",""),
("SPH-L300","Samsung","Galaxy Victory","Android",""),
("GT-I8550L","Samsung","Galaxy Win","Android",""),
("GT-S5360","Samsung","Galaxy Y","Android",""),
("GT-S6310N","Samsung","Galaxy Young","Android",""),
("GT-S6310","Samsung","Galaxy Young","Android",""),
("SAMSUNG-SGH-I997","Samsung","Infuse 4G","Android",""),
("Nexus_S","Samsung","Nexus S","Android",""),
("Nexus_S_4G","Samsung","Nexus S 4G","Android",""),
("SCH-S720C","Samsung","Proclaim","Android",""),
("SAMSUNG-SGH-I727","Samsung","Skyrocket","Android",""),
("SCH-I405","Samsung","Stratosphere","Android",""),
("SPH-M930BST","Samsung","Transform Ultra","Android",""),
("D2005","Sony","Xperia E1","Android",""),
("ST26i","Sony","Xperia J","Android",""),
("C2105","Sony","Xperia L","Android",""),
("C1905","Sony","Xperia M","Android",""),
("D2303","Sony","Xperia M2","Android",""),
("LT22i","Sony","Xperia P","Android",""),
("LT26i","Sony","Xperia S","Android",""),
("C5303","Sony","Xperia SP","Android",""),
("SGP312","Sony","Xperia Tablet Z","Android",""),
("ST21i","Sony","Xperia Tipo","Android",""),
("ST25i","Sony","Xperia U","Android",""),
("LT25i","Sony","Xperia V","Android",""),
("C6603","Sony","Xperia Z","Android",""),
("C6606","Sony","Xperia Z","Android",""),
("C6833","Sony","Xperia Z Ultra","Android",""),
("C6903","Sony","Xperia Z1","Android",""),
("D5503","Sony","Xperia Z1","Android",""),
("C6916","Sony","Xperia Z1S","Android",""),
("D6503","Sony","Xperia Z2","Android",""),
("D5803","Sony","Xperia Z3 Compact","Android",""),
("9920","Star","Alps S9920","Android",""),
("N3","Star","NO.1 N3","Android",""),
("T-Mobile_G2","T-Mobile","G2","Android",""),
("T-Mobile_myTouch_Q","T-Mobile","myTouch Q","Android",""),
("QMV7A","Verizon","Ellipsis 7","Android",""),
("MI_3W","Xiaomi","Mi 3","Android",""),
("N860","ZTE","Warp N860","Android","");