<?php $devicesDictionary=["A1-810"=>["manufacturer"=>"Acer","model"=>"Iconia A1-810","platform"=>"Android"],
"ALCATEL_ONE_TOUCH_Fierce"=>["manufacturer"=>"Alcatel","model"=>"One Touch Fierce","platform"=>"Android"],
"ALCATEL_ONE_TOUCH_7041X"=>["manufacturer"=>"Alcatel","model"=>"One Touch Pop C7","platform"=>"Android"],
"ALCATEL_ONE_TOUCH_5035X"=>["manufacturer"=>"Alcatel","model"=>"One Touch X Pop","platform"=>"Android"],
"google_sdk"=>["manufacturer"=>"Android","model"=>"Emulator","platform"=>"Android"],
"iPad1,1"=>["manufacturer"=>"Apple","model"=>"iPad","platform"=>"iOS","comment"=>"Original/1st Gen"],
"iPad2,1"=>["manufacturer"=>"Apple","model"=>"iPad 2","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad2,4"=>["manufacturer"=>"Apple","model"=>"iPad 2","platform"=>"iOS","comment"=>"Wi-Fi Only, 32nm CPU"],
"iPad2,3"=>["manufacturer"=>"Apple","model"=>"iPad 2","platform"=>"iOS","comment"=>"Wi-Fi/CDMA/GPS"],
"iPad2,2"=>["manufacturer"=>"Apple","model"=>"iPad 2","platform"=>"iOS","comment"=>"Wi-Fi/GSM/GPS"],
"iPad3,1"=>["manufacturer"=>"Apple","model"=>"iPad 3rd Gen","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad3,3"=>["manufacturer"=>"Apple","model"=>"iPad 3rd Gen","platform"=>"iOS","comment"=>"Wi-Fi/Cellular AT&T/GPS"],
"iPad3,2"=>["manufacturer"=>"Apple","model"=>"iPad 3rd Gen","platform"=>"iOS","comment"=>"Wi-Fi/Cellular Verizon/GPS"],
"iPad3,4"=>["manufacturer"=>"Apple","model"=>"iPad 4th Gen","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad3,5"=>["manufacturer"=>"Apple","model"=>"iPad 4th Gen","platform"=>"iOS","comment"=>"Wi-Fi/AT&T/GPS"],
"iPad3,6"=>["manufacturer"=>"Apple","model"=>"iPad 4th Gen","platform"=>"iOS","comment"=>"Wi-Fi/Verizon & Sprint/GPS"],
"iPad4,1"=>["manufacturer"=>"Apple","model"=>"iPad Air","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad4,2"=>["manufacturer"=>"Apple","model"=>"iPad Air","platform"=>"iOS","comment"=>"Wi-Fi/Cellular"],
"iPad4,3"=>["manufacturer"=>"Apple","model"=>"iPad Air","platform"=>"iOS","comment"=>"Wi-Fi/TD-LTE - China"],
"iPad5,3"=>["manufacturer"=>"Apple","model"=>"iPad Air 2","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad5,4"=>["manufacturer"=>"Apple","model"=>"iPad Air 2","platform"=>"iOS","comment"=>"Wi-Fi/Cellular"],
"iPad2,5"=>["manufacturer"=>"Apple","model"=>"iPad mini","platform"=>"iOS","comment"=>"Wi-Fi Only/1st Gen"],
"iPad2,6"=>["manufacturer"=>"Apple","model"=>"iPad mini","platform"=>"iOS","comment"=>"Wi-Fi/AT&T/GPS - 1st Gen"],
"iPad2,7"=>["manufacturer"=>"Apple","model"=>"iPad mini","platform"=>"iOS","comment"=>"Wi-Fi/VZ & Sprint/GPS - 1st Gen"],
"iPad4,6"=>["manufacturer"=>"Apple","model"=>"iPad mini 2","platform"=>"iOS","comment"=>"Retina/2nd Gen, China"],
"iPad4,4"=>["manufacturer"=>"Apple","model"=>"iPad mini 2","platform"=>"iOS","comment"=>"Retina/2nd Gen, Wi-Fi Only"],
"iPad4,5"=>["manufacturer"=>"Apple","model"=>"iPad mini 2","platform"=>"iOS","comment"=>"Retina/2nd Gen, Wi-Fi/Cellular"],
"iPad4,7"=>["manufacturer"=>"Apple","model"=>"iPad mini 3","platform"=>"iOS","comment"=>"Wi-Fi Only"],
"iPad4,8"=>["manufacturer"=>"Apple","model"=>"iPad mini 3","platform"=>"iOS","comment"=>"Wi-Fi/Cellular"],
"iPhone1,1"=>["manufacturer"=>"Apple","model"=>"iPhone","platform"=>"iOS","comment"=>"Original/1st Gen/EDGE"],
"iPhone1,2"=>["manufacturer"=>"Apple","model"=>"iPhone 3G","platform"=>"iOS"],
"iPhone2,1"=>["manufacturer"=>"Apple","model"=>"iPhone 3GS","platform"=>"iOS"],
"iPhone3,3"=>["manufacturer"=>"Apple","model"=>"iPhone 4","platform"=>"iOS","comment"=>"CDMA/Verizon/Sprint"],
"iPhone3,1"=>["manufacturer"=>"Apple","model"=>"iPhone 4","platform"=>"iOS","comment"=>"GSM"],
"iPhone4,1"=>["manufacturer"=>"Apple","model"=>"iPhone 4S","platform"=>"iOS"],
"iPhone5,2"=>["manufacturer"=>"Apple","model"=>"iPhone 5","platform"=>"iOS","comment"=>"CDMA/LTE"],
"iPhone5,1"=>["manufacturer"=>"Apple","model"=>"iPhone 5","platform"=>"iOS","comment"=>"GSM/LTE"],
"iPhone5,4"=>["manufacturer"=>"Apple","model"=>"iPhone 5c","platform"=>"iOS","comment"=>"Global"],
"iPhone5,3"=>["manufacturer"=>"Apple","model"=>"iPhone 5c","platform"=>"iOS","comment"=>"GSM"],
"iPhone6,2"=>["manufacturer"=>"Apple","model"=>"iPhone 5s","platform"=>"iOS","comment"=>"Global"],
"iPhone6,1"=>["manufacturer"=>"Apple","model"=>"iPhone 5s","platform"=>"iOS","comment"=>"GSM"],
"iPhone7,2"=>["manufacturer"=>"Apple","model"=>"iPhone 6","platform"=>"iOS"],
"iPhone7,1"=>["manufacturer"=>"Apple","model"=>"iPhone 6 Plus","platform"=>"iOS"],
"iPod1,1"=>["manufacturer"=>"Apple","model"=>"iPod touch","platform"=>"iOS","comment"=>"Original/1st Gen"],
"iPod2,1"=>["manufacturer"=>"Apple","model"=>"iPod touch 2nd Gen","platform"=>"iOS"],
"iPod3,1"=>["manufacturer"=>"Apple","model"=>"iPod touch 3rd Gen","platform"=>"iOS"],
"iPod4,1"=>["manufacturer"=>"Apple","model"=>"iPod touch 4th Gen","platform"=>"iOS"],
"iPod5,1"=>["manufacturer"=>"Apple","model"=>"iPod touch 5th Gen","platform"=>"iOS"],
"Transformer_TF101"=>["manufacturer"=>"ASUS","model"=>"Eee Pad Transformer","platform"=>"Android"],
"Transformer_Prime_TF201"=>["manufacturer"=>"ASUS","model"=>"Eee Pad Transformer Prime","platform"=>"Android"],
"ME173X"=>["manufacturer"=>"ASUS","model"=>"MeMO Pad HD 7","platform"=>"Android"],
"Nexus_7"=>["manufacturer"=>"ASUS","model"=>"Nexus 7","platform"=>"Android"],
"ASUS_Transformer_Pad_TF300T"=>["manufacturer"=>"ASUS","model"=>"Transformer Pad","platform"=>"Android"],
"ASUS_Transformer_Pad_TF700T"=>["manufacturer"=>"ASUS","model"=>"Transformer Pad Infinity","platform"=>"Android"],
"bq_Aquaris_5"=>["manufacturer"=>"bq","model"=>"Aquaris 5","platform"=>"Android"],
"bq_Aquaris_5_HD"=>["manufacturer"=>"bq","model"=>"Aquaris 5 HD","platform"=>"Android"],
"Aquaris_E4.5"=>["manufacturer"=>"bq","model"=>"Aquaris E4.5","platform"=>"Android"],
"5860E"=>["manufacturer"=>"Coolpad","model"=>"Quattro 4G","platform"=>"Android"],
"CUBOT_ONE"=>["manufacturer"=>"Cubot","model"=>"One","platform"=>"Android"],
"Nexus_10"=>["manufacturer"=>"Google","model"=>"Nexus 10","platform"=>"Android"],
"Nexus_4"=>["manufacturer"=>"Google","model"=>"Nexus 4","platform"=>"Android"],
"HTC_Amaze_4G"=>["manufacturer"=>"HTC","model"=>"Amaze 4G","platform"=>"Android"],
"HTC_Desire"=>["manufacturer"=>"HTC","model"=>"Desire","platform"=>"Android"],
"HTC_Desire_500"=>["manufacturer"=>"HTC","model"=>"Desire 500","platform"=>"Android"],
"HTC_Desire_C"=>["manufacturer"=>"HTC","model"=>"Desire C","platform"=>"Android"],
"Desire_HD"=>["manufacturer"=>"HTC","model"=>"Desire HD","platform"=>"Android"],
"HTC_Desire_HD_A9191"=>["manufacturer"=>"HTC","model"=>"Desire HD","platform"=>"Android"],
"HTC_Desire_S"=>["manufacturer"=>"HTC","model"=>"Desire S","platform"=>"Android"],
"HTC6435LVW"=>["manufacturer"=>"HTC","model"=>"Droid DNA","platform"=>"Android"],
"ADR6300"=>["manufacturer"=>"HTC","model"=>"Droid Incredible","platform"=>"Android"],
"ADR6350"=>["manufacturer"=>"HTC","model"=>"Droid Incredible 2","platform"=>"Android"],
"ADR6410LVW"=>["manufacturer"=>"HTC","model"=>"Droid Incredible 4G","platform"=>"Android"],
"EVO"=>["manufacturer"=>"HTC","model"=>"Evo","platform"=>"Android"],
"PG86100"=>["manufacturer"=>"HTC","model"=>"Evo 3D","platform"=>"Android"],
"PC36100"=>["manufacturer"=>"HTC","model"=>"Evo 4G","platform"=>"Android"],
"HTCEVODesign4G"=>["manufacturer"=>"HTC","model"=>"Evo Design 4G","platform"=>"Android"],
"PH44100"=>["manufacturer"=>"HTC","model"=>"Evo Design 4G","platform"=>"Android"],
"PG06100"=>["manufacturer"=>"HTC","model"=>"EVO Shift 4G","platform"=>"Android"],
"HTCEVOV4G"=>["manufacturer"=>"HTC","model"=>"Evo V 4G","platform"=>"Android"],
"HTC_Glacier"=>["manufacturer"=>"HTC","model"=>"Glacier","platform"=>"Android"],
"HTC_Incredible_S"=>["manufacturer"=>"HTC","model"=>"Incredible S","platform"=>"Android"],
"myTouch_4G_Slide"=>["manufacturer"=>"HTC","model"=>"myTouch 4G Slide","platform"=>"Android"],
"HTC6500LVW"=>["manufacturer"=>"HTC","model"=>"One","platform"=>"Android"],
"HTC_One"=>["manufacturer"=>"HTC","model"=>"One","platform"=>"Android"],
"HTCONE"=>["manufacturer"=>"HTC","model"=>"One","platform"=>"Android"],
"HTC_PN071"=>["manufacturer"=>"HTC","model"=>"One","platform"=>"Android"],
"831C"=>["manufacturer"=>"HTC","model"=>"One M8","platform"=>"Android"],
"HTC6525LVW"=>["manufacturer"=>"HTC","model"=>"One M8","platform"=>"Android"],
"HTC_One_M8"=>["manufacturer"=>"HTC","model"=>"One M8","platform"=>"Android"],
"HTC_One_mini"=>["manufacturer"=>"HTC","model"=>"One mini","platform"=>"Android"],
"HTC_One_S"=>["manufacturer"=>"HTC","model"=>"One S","platform"=>"Android"],
"HTC_VLE_U"=>["manufacturer"=>"HTC","model"=>"One S","platform"=>"Android"],
"HTC_One_V"=>["manufacturer"=>"HTC","model"=>"One V","platform"=>"Android"],
"HTC_One_X"=>["manufacturer"=>"HTC","model"=>"One X","platform"=>"Android"],
"HTC_One_X+"=>["manufacturer"=>"HTC","model"=>"One X+","platform"=>"Android"],
"ADR6425LVW"=>["manufacturer"=>"HTC","model"=>"Rezound 4G","platform"=>"Android"],
"ADR6330VW"=>["manufacturer"=>"HTC","model"=>"Rhyme","platform"=>"Android"],
"HTC_Sensation_Z710e"=>["manufacturer"=>"HTC","model"=>"Sensation","platform"=>"Android"],
"HTC_Sensation_4G"=>["manufacturer"=>"HTC","model"=>"Sensation 4G","platform"=>"Android"],
"ADR6400L"=>["manufacturer"=>"HTC","model"=>"Thunderbolt","platform"=>"Android"],
"HTC_PH39100"=>["manufacturer"=>"HTC","model"=>"Vivid 4G","platform"=>"Android"],
"HUAWEI_G510-0251"=>["manufacturer"=>"Huawei","model"=>"Ascend G510","platform"=>"Android"],
"Orange_Daytona"=>["manufacturer"=>"Huawei","model"=>"Ascend G510","platform"=>"Android"],
"HUAWEI_P6-U06"=>["manufacturer"=>"Huawei","model"=>"Ascend P6","platform"=>"Android"],
"HUAWEI_Y300-0100"=>["manufacturer"=>"Huawei","model"=>"Ascend Y300","platform"=>"Android"],
"CM990"=>["manufacturer"=>"Huawei","model"=>"Evolution III","platform"=>"Android"],
"KFOT"=>["manufacturer"=>"Kindle","model"=>"Fire","platform"=>"Android"],
"Kindle_Fire"=>["manufacturer"=>"Kindle","model"=>"Fire","platform"=>"Android"],
"KFTT"=>["manufacturer"=>"Kindle","model"=>"Fire HD 7","platform"=>"Android"],
"KFJWA"=>["manufacturer"=>"Kindle","model"=>"Fire HD 8.9","platform"=>"Android"],
"KFJWI"=>["manufacturer"=>"Kindle","model"=>"Fire HD 8.9","platform"=>"Android"],
"C5170"=>["manufacturer"=>"Kyocera","model"=>"Hydro","platform"=>"Android"],
"C5155"=>["manufacturer"=>"Kyocera","model"=>"Rise","platform"=>"Android"],
"LG-MS910"=>["manufacturer"=>"LG","model"=>"Esteem","platform"=>"Android"],
"LG-D686"=>["manufacturer"=>"LG","model"=>"G Pro Lite Dual","platform"=>"Android"],
"LG-D800"=>["manufacturer"=>"LG","model"=>"G2","platform"=>"Android"],
"LG-D801"=>["manufacturer"=>"LG","model"=>"G2","platform"=>"Android"],
"LG-D802"=>["manufacturer"=>"LG","model"=>"G2","platform"=>"Android"],
"LG-LS980"=>["manufacturer"=>"LG","model"=>"G2","platform"=>"Android"],
"VS980_4G"=>["manufacturer"=>"LG","model"=>"G2","platform"=>"Android"],
"LG-D620"=>["manufacturer"=>"LG","model"=>"G2 Mini","platform"=>"Android"],
"LG-P999"=>["manufacturer"=>"LG","model"=>"G2X P999","platform"=>"Android"],
"LG-D850"=>["manufacturer"=>"LG","model"=>"G3","platform"=>"Android"],
"LG-D851"=>["manufacturer"=>"LG","model"=>"G3","platform"=>"Android"],
"LG-D855"=>["manufacturer"=>"LG","model"=>"G3","platform"=>"Android"],
"VS985_4G"=>["manufacturer"=>"LG","model"=>"G3 4G","platform"=>"Android"],
"VS840_4G"=>["manufacturer"=>"LG","model"=>"Lucid 4G","platform"=>"Android"],
"LG-MS770"=>["manufacturer"=>"LG","model"=>"Motion 4G","platform"=>"Android"],
"LG-E739"=>["manufacturer"=>"LG","model"=>"MyTouch e739","platform"=>"Android"],
"LG-C800"=>["manufacturer"=>"LG","model"=>"myTouch Q","platform"=>"Android"],
"LG-VM696"=>["manufacturer"=>"LG","model"=>"Optimus Elite","platform"=>"Android"],
"LG-LS720"=>["manufacturer"=>"LG","model"=>"Optimus F3","platform"=>"Android"],
"LGMS500"=>["manufacturer"=>"LG","model"=>"Optimus F6","platform"=>"Android"],
"LG-E970"=>["manufacturer"=>"LG","model"=>"Optimus G","platform"=>"Android"],
"LG-LS970"=>["manufacturer"=>"LG","model"=>"Optimus G","platform"=>"Android"],
"LG-E980"=>["manufacturer"=>"LG","model"=>"Optimus G Pro","platform"=>"Android"],
"LG-E411g"=>["manufacturer"=>"LG","model"=>"Optimus L1 II","platform"=>"Android"],
"LG-E425g"=>["manufacturer"=>"LG","model"=>"Optimus L3 II","platform"=>"Android"],
"LG-E440g"=>["manufacturer"=>"LG","model"=>"Optimus L4 II","platform"=>"Android"],
"LG-E610"=>["manufacturer"=>"LG","model"=>"Optimus L5","platform"=>"Android"],
"LG-E612g"=>["manufacturer"=>"LG","model"=>"Optimus L5 Dual","platform"=>"Android"],
"LG-E460"=>["manufacturer"=>"LG","model"=>"Optimus L5 II","platform"=>"Android"],
"LGMS323"=>["manufacturer"=>"LG","model"=>"Optimus L70","platform"=>"Android"],
"LGMS769"=>["manufacturer"=>"LG","model"=>"Optimus L9","platform"=>"Android"],
"LG-P760"=>["manufacturer"=>"LG","model"=>"Optimus L9","platform"=>"Android"],
"LG-P768"=>["manufacturer"=>"LG","model"=>"Optimus L9","platform"=>"Android"],
"LG-P769"=>["manufacturer"=>"LG","model"=>"Optimus L9","platform"=>"Android"],
"LG-D415"=>["manufacturer"=>"LG","model"=>"Optimus L90","platform"=>"Android"],
"LGL55C"=>["manufacturer"=>"LG","model"=>"Optimus Q","platform"=>"Android"],
"LS670"=>["manufacturer"=>"LG","model"=>"Optimus S","platform"=>"Android"],
"LG-P509"=>["manufacturer"=>"LG","model"=>"Optimus T","platform"=>"Android"],
"VM670"=>["manufacturer"=>"LG","model"=>"Optimus V","platform"=>"Android"],
"VS910_4G"=>["manufacturer"=>"LG","model"=>"Revolution 4G","platform"=>"Android"],
"VS930_4G"=>["manufacturer"=>"LG","model"=>"Spectrum 2","platform"=>"Android"],
"VS920_4G"=>["manufacturer"=>"LG","model"=>"Spectrum 4G","platform"=>"Android"],
"LG-LG730"=>["manufacturer"=>"LG","model"=>"Venice","platform"=>"Android"],
"LG-LS840"=>["manufacturer"=>"LG","model"=>"Viper","platform"=>"Android"],
"LGLS740"=>["manufacturer"=>"LG","model"=>"Volt","platform"=>"Android"],
"MB865"=>["manufacturer"=>"Motorola","model"=>"Atrix 2","platform"=>"Android"],
"MB860"=>["manufacturer"=>"Motorola","model"=>"Atrix 4G","platform"=>"Android"],
"MB886"=>["manufacturer"=>"Motorola","model"=>"Atrix HD","platform"=>"Android"],
"Droid"=>["manufacturer"=>"Motorola","model"=>"Droid","platform"=>"Android"],
"DROID2"=>["manufacturer"=>"Motorola","model"=>"Droid 2","platform"=>"Android"],
"DROID2_GLOBAL"=>["manufacturer"=>"Motorola","model"=>"Droid 2 Global","platform"=>"Android"],
"DROID3"=>["manufacturer"=>"Motorola","model"=>"Droid 3","platform"=>"Android"],
"DROID4"=>["manufacturer"=>"Motorola","model"=>"Droid 4","platform"=>"Android"],
"DROID_BIONIC"=>["manufacturer"=>"Motorola","model"=>"Droid Bionic","platform"=>"Android"],
"XT1030"=>["manufacturer"=>"Motorola","model"=>"Droid Mini","platform"=>"Android"],
"DROID_Pro"=>["manufacturer"=>"Motorola","model"=>"Droid Pro","platform"=>"Android"],
"DROID_RAZR"=>["manufacturer"=>"Motorola","model"=>"Droid Razr","platform"=>"Android"],
"DROID_RAZR_HD"=>["manufacturer"=>"Motorola","model"=>"Droid Razr HD","platform"=>"Android"],
"XT907"=>["manufacturer"=>"Motorola","model"=>"Droid Razr M","platform"=>"Android"],
"XT1080"=>["manufacturer"=>"Motorola","model"=>"Droid Ultra","platform"=>"Android"],
"DROIDX"=>["manufacturer"=>"Motorola","model"=>"Droid X","platform"=>"Android"],
"DROID_X2"=>["manufacturer"=>"Motorola","model"=>"Droid X2","platform"=>"Android"],
"Motorola_Electrify"=>["manufacturer"=>"Motorola","model"=>"Electrify","platform"=>"Android"],
"XT1028"=>["manufacturer"=>"Motorola","model"=>"Moto G","platform"=>"Android"],
"XT1031"=>["manufacturer"=>"Motorola","model"=>"Moto G","platform"=>"Android"],
"XT1032"=>["manufacturer"=>"Motorola","model"=>"Moto G","platform"=>"Android"],
"XT1033"=>["manufacturer"=>"Motorola","model"=>"Moto G","platform"=>"Android"],
"XT1049"=>["manufacturer"=>"Motorola","model"=>"Moto X","platform"=>"Android"],
"XT1053"=>["manufacturer"=>"Motorola","model"=>"Moto X","platform"=>"Android"],
"XT1056"=>["manufacturer"=>"Motorola","model"=>"Moto X","platform"=>"Android"],
"XT1058"=>["manufacturer"=>"Motorola","model"=>"Moto X","platform"=>"Android"],
"XT1060"=>["manufacturer"=>"Motorola","model"=>"Moto X","platform"=>"Android"],
"XT897"=>["manufacturer"=>"Motorola","model"=>"Photo Q","platform"=>"Android"],
"MB855"=>["manufacturer"=>"Motorola","model"=>"Photon 4G","platform"=>"Android"],
"MOTWX435KT"=>["manufacturer"=>"Motorola","model"=>"Triumph","platform"=>"Android"],
"Xoom"=>["manufacturer"=>"Motorola","model"=>"Xoom","platform"=>"Android"],
"Nexus_5"=>["manufacturer"=>"Nexus","model"=>"5","platform"=>"Android"],
"A0001"=>["manufacturer"=>"OnePlus","model"=>"One","platform"=>"Android"],
"PantechP9070"=>["manufacturer"=>"Pantech","model"=>"Burst","platform"=>"Android"],
"SCH-R720"=>["manufacturer"=>"Samsung","model"=>"Admire","platform"=>"Android"],
"SAMSUNG-SGH-I897"=>["manufacturer"=>"Samsung","model"=>"Captivate","platform"=>"Android"],
"SAMSUNG-SGH-I927"=>["manufacturer"=>"Samsung","model"=>"Captivate Glide","platform"=>"Android"],
"SPH-D600"=>["manufacturer"=>"Samsung","model"=>"Conquer 4G","platform"=>"Android"],
"SCH-I510"=>["manufacturer"=>"Samsung","model"=>"Droid Charge","platform"=>"Android"],
"SPH-D710"=>["manufacturer"=>"Samsung","model"=>"Epic","platform"=>"Android"],
"SPH-D700"=>["manufacturer"=>"Samsung","model"=>"Epic 4G","platform"=>"Android"],
"SGH-T679"=>["manufacturer"=>"Samsung","model"=>"Exhibit II","platform"=>"Android"],
"SCH-I500"=>["manufacturer"=>"Samsung","model"=>"Fascinate","platform"=>"Android"],
"GT-S5830i"=>["manufacturer"=>"Samsung","model"=>"Galaxy Ace","platform"=>"Android"],
"GT-S5830"=>["manufacturer"=>"Samsung","model"=>"Galaxy Ace","platform"=>"Android"],
"GT-I8160"=>["manufacturer"=>"Samsung","model"=>"Galaxy Ace 2","platform"=>"Android"],
"GT-S7560M"=>["manufacturer"=>"Samsung","model"=>"Galaxy Ace II X","platform"=>"Android"],
"SCH-S738C"=>["manufacturer"=>"Samsung","model"=>"Galaxy Centura","platform"=>"Android"],
"GT-I8260"=>["manufacturer"=>"Samsung","model"=>"Galaxy Core","platform"=>"Android"],
"SGH-T599N"=>["manufacturer"=>"Samsung","model"=>"Galaxy Exhibit","platform"=>"Android"],
"SM-G3815"=>["manufacturer"=>"Samsung","model"=>"Galaxy Express II","platform"=>"Android"],
"GT-S6810P"=>["manufacturer"=>"Samsung","model"=>"Galaxy Fame","platform"=>"Android"],
"GT-I9082"=>["manufacturer"=>"Samsung","model"=>"Galaxy Grand","platform"=>"Android"],
"SM-G7102"=>["manufacturer"=>"Samsung","model"=>"Galaxy Grand II","platform"=>"Android"],
"GT-I9060"=>["manufacturer"=>"Samsung","model"=>"Galaxy Grand Neo","platform"=>"Android"],
"GT-I9063T"=>["manufacturer"=>"Samsung","model"=>"Galaxy Grand Neo Duos","platform"=>"Android"],
"SGH-T399"=>["manufacturer"=>"Samsung","model"=>"Galaxy Light","platform"=>"Android"],
"SAMSUNG-SGH-I527"=>["manufacturer"=>"Samsung","model"=>"Galaxy Mega","platform"=>"Android"],
"GT-S5570"=>["manufacturer"=>"Samsung","model"=>"Galaxy Mini","platform"=>"Android"],
"Galaxy_Nexus"=>["manufacturer"=>"Samsung","model"=>"Galaxy Nexus","platform"=>"Android"],
"GT-N7000"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note","platform"=>"Android"],
"SAMSUNG-SGH-I717"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note","platform"=>"Android"],
"GT-N8010"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 10.1","platform"=>"Android"],
"GT-N8013"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 10.1","platform"=>"Android"],
"SM-P600"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 10.1","platform"=>"Android"],
"SAMSUNG-SM-N900A"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N9005"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N9006"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N900P"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N900"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N900T"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N900V"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N900W8"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3","platform"=>"Android"],
"SM-N7505"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 3 Neo","platform"=>"Android"],
"SAMSUNG-SM-N910A"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 4","platform"=>"Android"],
"SM-N910T"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 4","platform"=>"Android"],
"SM-N910V"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 4","platform"=>"Android"],
"GT-N5110"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note 8.0","platform"=>"Android"],
"GT-N7100"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"GT-N7105"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"GT-N7105T"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SAMSUNG-SGH-I317"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SCH-I605"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SGH-I317M"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SGH-T889"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SHV-E250S"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"SPH-L900"=>["manufacturer"=>"Samsung","model"=>"Galaxy Note II","platform"=>"Android"],
"GT-S5301L"=>["manufacturer"=>"Samsung","model"=>"Galaxy Pocket Plus","platform"=>"Android"],
"SPH-M820-BST"=>["manufacturer"=>"Samsung","model"=>"Galaxy Prevail","platform"=>"Android"],
"SPH-M840"=>["manufacturer"=>"Samsung","model"=>"Galaxy Prevail 2","platform"=>"Android"],
"SPH-M830"=>["manufacturer"=>"Samsung","model"=>"Galaxy Rush","platform"=>"Android"],
"GT-I9000"=>["manufacturer"=>"Samsung","model"=>"Galaxy S","platform"=>"Android"],
"SGH-T959V"=>["manufacturer"=>"Samsung","model"=>"Galaxy S 4G","platform"=>"Android"],
"GT-I9070"=>["manufacturer"=>"Samsung","model"=>"Galaxy S Advance","platform"=>"Android"],
"SGH-T769"=>["manufacturer"=>"Samsung","model"=>"Galaxy S Blaze","platform"=>"Android"],
"GT-S7562"=>["manufacturer"=>"Samsung","model"=>"Galaxy S Duos","platform"=>"Android"],
"GT-I9100M"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"GT-I9100P"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"GT-I9100"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"GT-I9100T"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SAMSUNG-SGH-I777"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SGH-I727R"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SGH-T989D"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SGH-T989"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SPH-D710BST"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"SPH-D710VMUB"=>["manufacturer"=>"Samsung","model"=>"Galaxy S II","platform"=>"Android"],
"GT-I9300"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"GT-I9300T"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"GT-I9305"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"GT-I9305T"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SAMSUNG-SGH-I747"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SCH-I535"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SCH-R530M"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SCH-R530U"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SGH-I747M"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SGH-T999L"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SGH-T999"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SGH-T999V"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SHV-E210S"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"SPH-L710"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III","platform"=>"Android"],
"GT-I8190N"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III Mini","platform"=>"Android"],
"GT-I8190"=>["manufacturer"=>"Samsung","model"=>"Galaxy S III Mini","platform"=>"Android"],
"GT-I9001"=>["manufacturer"=>"Samsung","model"=>"Galaxy S Plus","platform"=>"Android"],
"SGH-T959"=>["manufacturer"=>"Samsung","model"=>"Galaxy S Vibrant","platform"=>"Android"],
"GT-I9105P"=>["manufacturer"=>"Samsung","model"=>"Galaxy S2 Plus","platform"=>"Android"],
"SCH-R530C"=>["manufacturer"=>"Samsung","model"=>"Galaxy S3","platform"=>"Android"],
"SHV-E210K"=>["manufacturer"=>"Samsung","model"=>"Galaxy S3","platform"=>"Android"],
"GT-I8190L"=>["manufacturer"=>"Samsung","model"=>"Galaxy S3 Mini","platform"=>"Android"],
"SAMSUNG-SM-G730A"=>["manufacturer"=>"Samsung","model"=>"Galaxy S3 Mini","platform"=>"Android"],
"GT-I9500"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"GT-I9505"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"GT-I9506"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SAMSUNG-SGH-I337"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SCH-I545"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SCH-R970"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SGH-I337M"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SGH-M919"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SPH-L720"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SPH-L720T"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4","platform"=>"Android"],
"SAMSUNG-SGH-I537"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4 Active","platform"=>"Android"],
"GT-I9195"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4 Mini","platform"=>"Android"],
"SCH-I435"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4 Mini","platform"=>"Android"],
"GT-I9192"=>["manufacturer"=>"Samsung","model"=>"Galaxy S4 Mini Duos","platform"=>"Android"],
"SAMSUNG-SM-G900A"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900F"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900I"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900P"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900T"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900V"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SM-G900W8"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5","platform"=>"Android"],
"SAMSUNG-SM-G870A"=>["manufacturer"=>"Samsung","model"=>"Galaxy S5 Active","platform"=>"Android"],
"SCH-I200"=>["manufacturer"=>"Samsung","model"=>"Galaxy Stellar","platform"=>"Android"],
"SCH-I415"=>["manufacturer"=>"Samsung","model"=>"Galaxy Stratosphere II","platform"=>"Android"],
"GT-P7510"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 10.1","platform"=>"Android"],
"GT-P3100"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 2","platform"=>"Android"],
"GT-P3110"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 2","platform"=>"Android"],
"GT-P5110"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 2","platform"=>"Android"],
"GT-P5113"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 2 10.1","platform"=>"Android"],
"GT-P3113"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 2 7.0","platform"=>"Android"],
"GT-P5210"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 3 10.1","platform"=>"Android"],
"SM-T210R"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 3 7.0","platform"=>"Android"],
"SM-T217S"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 3 7.0","platform"=>"Android"],
"SM-T310"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 3 8.0","platform"=>"Android"],
"SCH-I800"=>["manufacturer"=>"Samsung","model"=>"Galaxy Tab 7.0","platform"=>"Android"],
"GT-S7580"=>["manufacturer"=>"Samsung","model"=>"Galaxy Trend Plus","platform"=>"Android"],
"SPH-L300"=>["manufacturer"=>"Samsung","model"=>"Galaxy Victory","platform"=>"Android"],
"GT-I8550L"=>["manufacturer"=>"Samsung","model"=>"Galaxy Win","platform"=>"Android"],
"GT-S5360"=>["manufacturer"=>"Samsung","model"=>"Galaxy Y","platform"=>"Android"],
"GT-S6310N"=>["manufacturer"=>"Samsung","model"=>"Galaxy Young","platform"=>"Android"],
"GT-S6310"=>["manufacturer"=>"Samsung","model"=>"Galaxy Young","platform"=>"Android"],
"SAMSUNG-SGH-I997"=>["manufacturer"=>"Samsung","model"=>"Infuse 4G","platform"=>"Android"],
"Nexus_S"=>["manufacturer"=>"Samsung","model"=>"Nexus S","platform"=>"Android"],
"Nexus_S_4G"=>["manufacturer"=>"Samsung","model"=>"Nexus S 4G","platform"=>"Android"],
"SCH-S720C"=>["manufacturer"=>"Samsung","model"=>"Proclaim","platform"=>"Android"],
"SAMSUNG-SGH-I727"=>["manufacturer"=>"Samsung","model"=>"Skyrocket","platform"=>"Android"],
"SCH-I405"=>["manufacturer"=>"Samsung","model"=>"Stratosphere","platform"=>"Android"],
"SPH-M930BST"=>["manufacturer"=>"Samsung","model"=>"Transform Ultra","platform"=>"Android"],
"D2005"=>["manufacturer"=>"Sony","model"=>"Xperia E1","platform"=>"Android"],
"ST26i"=>["manufacturer"=>"Sony","model"=>"Xperia J","platform"=>"Android"],
"C2105"=>["manufacturer"=>"Sony","model"=>"Xperia L","platform"=>"Android"],
"C1905"=>["manufacturer"=>"Sony","model"=>"Xperia M","platform"=>"Android"],
"D2303"=>["manufacturer"=>"Sony","model"=>"Xperia M2","platform"=>"Android"],
"LT22i"=>["manufacturer"=>"Sony","model"=>"Xperia P","platform"=>"Android"],
"LT26i"=>["manufacturer"=>"Sony","model"=>"Xperia S","platform"=>"Android"],
"C5303"=>["manufacturer"=>"Sony","model"=>"Xperia SP","platform"=>"Android"],
"SGP312"=>["manufacturer"=>"Sony","model"=>"Xperia Tablet Z","platform"=>"Android"],
"ST21i"=>["manufacturer"=>"Sony","model"=>"Xperia Tipo","platform"=>"Android"],
"ST25i"=>["manufacturer"=>"Sony","model"=>"Xperia U","platform"=>"Android"],
"LT25i"=>["manufacturer"=>"Sony","model"=>"Xperia V","platform"=>"Android"],
"C6603"=>["manufacturer"=>"Sony","model"=>"Xperia Z","platform"=>"Android"],
"C6606"=>["manufacturer"=>"Sony","model"=>"Xperia Z","platform"=>"Android"],
"C6833"=>["manufacturer"=>"Sony","model"=>"Xperia Z Ultra","platform"=>"Android"],
"C6903"=>["manufacturer"=>"Sony","model"=>"Xperia Z1","platform"=>"Android"],
"D5503"=>["manufacturer"=>"Sony","model"=>"Xperia Z1","platform"=>"Android"],
"C6916"=>["manufacturer"=>"Sony","model"=>"Xperia Z1S","platform"=>"Android"],
"D6503"=>["manufacturer"=>"Sony","model"=>"Xperia Z2","platform"=>"Android"],
"D5803"=>["manufacturer"=>"Sony","model"=>"Xperia Z3 Compact","platform"=>"Android"],
"9920"=>["manufacturer"=>"Star","model"=>"Alps S9920","platform"=>"Android"],
"N3"=>["manufacturer"=>"Star","model"=>"NO.1 N3","platform"=>"Android"],
"T-Mobile_G2"=>["manufacturer"=>"T-Mobile","model"=>"G2","platform"=>"Android"],
"T-Mobile_myTouch_Q"=>["manufacturer"=>"T-Mobile","model"=>"myTouch Q","platform"=>"Android"],
"QMV7A"=>["manufacturer"=>"Verizon","model"=>"Ellipsis 7","platform"=>"Android"],
"MI_3W"=>["manufacturer"=>"Xiaomi","model"=>"Mi 3","platform"=>"Android"],
"N860"=>["manufacturer"=>"ZTE","model"=>"Warp N860","platform"=>"Android"]];